[package]
name = "xagima"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
voladdress = "1.0.2"
spin = "0.9.2"
x86_64 = "0.14.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"